set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR avr)

find_program(AVR_GCC avr-gcc REQUIRED)
find_program(AVR_GXX avr-g++ REQUIRED)
find_program(AVR_GCC_AR avr-gcc-ar)
find_program(AVR_RANLIB avr-gcc-ranlib)
find_program(AVR_OBJCOPY avr-objcopy REQUIRED)
find_program(AVR_SIZE avr-size REQUIRED)

set(CMAKE_C_COMPILER "${AVR_GCC}")
set(CMAKE_CXX_COMPILER "${AVR_GXX}")
set(CMAKE_AR "${AVR_GCC_AR}" CACHE FILEPATH "" FORCE)
set(CMAKE_RANLIB "${AVR_RANLIB}" CACHE FILEPATH "" FORCE)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(CMAKE_C_STANDARD 11)
set(CMAKE_C_STANDARD_REQUIRED ON)
set(CMAKE_C_EXTENSIONS OFF)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
